/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9ff",
        "tertiary-container": "#3c2700",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ad8d5b",
        "tertiary-fixed": "#ffdead",
        "on-tertiary-fixed": "#281900",
        "background": "#f8f9ff",
        "tertiary": "#211400",
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "primary-fixed": "#d7e2ff",
        "on-primary-fixed": "#081b38",
        "primary-container": "#1a2b48",
        "inverse-primary": "#b6c7eb",
        "on-surface-variant": "#44474d",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-highest": "#d3e4fe",
        "outline": "#75777e",
        "secondary-fixed": "#d8e2ff",
        "on-secondary-container": "#fefcff",
        "on-background": "#0b1c30",
        "secondary-container": "#2170e4",
        "tertiary-fixed-dim": "#e5c18a",
        "primary-fixed-dim": "#b6c7eb",
        "on-error-container": "#93000a",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#374765",
        "outline-variant": "#c5c6ce",
        "on-surface": "#0b1c30",
        "secondary-fixed-dim": "#adc6ff",
        "primary": "#031632",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#213145",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#004395",
        "secondary": "#0058be",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#5b4217",
        "surface-container": "#e5eeff",
        "surface-tint": "#4e5f7e",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-primary-container": "#8293b5",
        "on-primary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}